"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Archive, Beaker, Droplets, History, PackagePlus, Pencil, Plus, Sparkles, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/sonner";

type Product = { id: number; name: string; category: string; unit: string; packageSize: number; remaining: number; lowThreshold: number; phType: "酸性" | "中性" | "鹼性"; affectedFlowNames: string | null };
type FlowItem = { flowId: number; productId: number; amount: number; productName: string; unit: string };
type WashFlow = { id: number; name: string; flowType: string; items: FlowItem[] };
type Wash = { id: string; washedAt: string; note: string | null; flowName: string | null; summary: string | null };
type Data = { products: Product[]; flows: WashFlow[]; washes: Wash[] };
type Submit = (action: string, payload: Record<string, unknown>) => Promise<void>;
const inputClass = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-cyan-600 focus:ring-4 focus:ring-cyan-600/10 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400";

export default function InventoryApp() {
  const [data, setData] = useState<Data>({ products: [], flows: [], washes: [] });
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const [addOpen, setAddOpen] = useState(false), [washOpen, setWashOpen] = useState(false), [flowOpen, setFlowOpen] = useState(false);
  const [restock, setRestock] = useState<Product | null>(null), [deleting, setDeleting] = useState<Product | null>(null), [editingFlow, setEditingFlow] = useState<WashFlow | null>(null);
  const guard = useRef(false);
  const load = useCallback(async () => { const r = await fetch("/api/inventory", { cache: "no-store" }); if (!r.ok) throw new Error(); setData(await r.json()); setLoading(false); }, []);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load().catch(() => { setLoading(false); toast.error("暫時無法讀取庫存"); });
  }, [load]);
  const submit: Submit = async (action, payload) => {
    if (guard.current) throw new Error("操作正在處理中，請稍候");
    guard.current = true; setBusy(true);
    try { const r = await fetch("/api/inventory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const result = await r.json().catch(() => ({})); if (!r.ok) throw new Error(result.error || "操作失敗"); await load(); }
    finally { guard.current = false; setBusy(false); }
  };
  const lowStock = useMemo(() => data.products.filter((p) => p.remaining <= p.lowThreshold), [data.products]);
  const average = data.products.length ? Math.round(data.products.reduce((s, p) => s + Math.min(100, p.remaining / p.packageSize * 100), 0) / data.products.length) : 0;
  return <main className="min-h-screen bg-[#f2f7f7] text-slate-950"><Toaster position="top-center" richColors />
    <header className="border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-2xl bg-cyan-950 text-cyan-100"><Droplets className="size-5" /></div><div><p className="text-xs font-semibold tracking-[.18em] text-cyan-700">CAR CARE</p><h1 className="font-semibold tracking-tight">洗車用品庫存</h1></div></div><Button disabled={busy} onClick={() => setWashOpen(true)} className="rounded-xl bg-cyan-950 text-white hover:bg-cyan-900"><Sparkles className="size-4" />記錄洗車</Button></div></header>
    <div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 sm:py-10">
      <section className="grid gap-4 md:grid-cols-[1.45fr_.8fr_.8fr]"><div className="relative overflow-hidden rounded-[28px] bg-cyan-950 p-6 text-white shadow-[0_18px_55px_rgba(8,51,68,.17)] sm:p-8"><div className="absolute -right-16 -top-20 size-52 rounded-full border-[28px] border-cyan-700/30" /><p className="text-sm text-cyan-200">目前庫存概況</p><div className="mt-8 flex items-end gap-3"><strong className="text-6xl font-semibold tracking-[-.06em]">{loading ? "—" : average}</strong><span className="pb-2 text-cyan-200">% 平均剩餘</span></div><p className="mt-3 text-sm text-cyan-100/75">共管理 {data.products.length} 項用品</p></div><Metric icon={<Archive />} value={data.products.length} label="庫存品項" /><Metric icon={<AlertTriangle />} value={lowStock.length} label="需要補貨" warning={lowStock.length > 0} /></section>
      <Tabs defaultValue="inventory" className="mt-9"><TabsList className="w-full justify-start rounded-2xl bg-white p-1 sm:w-fit"><TabsTrigger value="inventory" className="rounded-xl px-4">用品庫存</TabsTrigger><TabsTrigger value="flows" className="rounded-xl px-4">流程管理</TabsTrigger><TabsTrigger value="history" className="rounded-xl px-4">洗車紀錄</TabsTrigger></TabsList>
        <TabsContent value="inventory" className="mt-6"><SectionTitle eyebrow="INVENTORY" title="用品餘量"><AddProductDialog open={addOpen} setOpen={setAddOpen} submit={submit} busy={busy} /></SectionTitle>{loading ? <Loading /> : data.products.length === 0 ? <EmptyState onAdd={() => setAddOpen(true)} /> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.products.map((p) => <ProductCard key={p.id} product={p} onRestock={() => setRestock(p)} onDelete={() => setDeleting(p)} />)}</div>}</TabsContent>
        <TabsContent value="flows" className="mt-6"><SectionTitle eyebrow="WASH ROUTINES" title="洗車流程"><Button variant="outline" className="rounded-xl" onClick={() => { setEditingFlow(null); setFlowOpen(true); }}><Plus />自訂流程</Button></SectionTitle><div className="grid gap-4 md:grid-cols-3">{data.flows.map((flow) => <article key={flow.id} className="rounded-3xl border border-white bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-cyan-50 px-3 py-1 text-xs font-semibold text-cyan-800">{flow.flowType}</span><button aria-label={`編輯 ${flow.name}`} onClick={() => { setEditingFlow(flow); setFlowOpen(true); }} className="grid size-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100 hover:text-cyan-800"><Pencil className="size-4" /></button></div><h3 className="mt-4 text-lg font-semibold">{flow.name}</h3>{flow.items.length ? <div className="mt-4 space-y-2">{flow.items.map((item) => <div key={item.productId} className="flex justify-between text-sm"><span className="text-slate-600">{item.productName}</span><span className="font-medium">{format(item.amount)} {item.unit}</span></div>)}</div> : <p className="mt-4 text-sm text-amber-700">尚未設定藥劑，請點右上角編輯。</p>}</article>)}</div></TabsContent>
        <TabsContent value="history" className="mt-6"><HistoryList washes={data.washes} /></TabsContent>
      </Tabs>
    </div>
    <WashDialog open={washOpen} setOpen={setWashOpen} flows={data.flows} products={data.products} submit={submit} busy={busy} />
    <FlowDialog open={flowOpen} setOpen={setFlowOpen} flow={editingFlow} products={data.products} submit={submit} busy={busy} />
    <RestockDialog product={restock} setProduct={setRestock} submit={submit} busy={busy} />
    <DeleteProductDialog product={deleting} setProduct={setDeleting} submit={submit} busy={busy} />
  </main>;
}

function ProductCard({ product: p, onRestock, onDelete }: { product: Product; onRestock: () => void; onDelete: () => void }) { const percent = Math.max(0, Math.min(100, p.remaining / p.packageSize * 100)), low = p.remaining <= p.lowThreshold; return <article className="rounded-3xl border border-white bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{p.category}</span><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${phClass(p.phType)}`}>{p.phType}</span></div>{low && <span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-medium text-amber-800">補貨</span>}</div><h3 className="mt-3 font-semibold">{p.name}</h3><div className="mt-8 flex items-baseline justify-between"><span className="text-3xl font-semibold tracking-tight">{format(p.remaining)}</span><span className="text-sm text-slate-500">{p.unit} / {format(p.packageSize)} {p.unit}</span></div><Progress value={percent} className={`mt-3 h-2 ${low ? "[&_[data-slot=progress-indicator]]:bg-amber-500" : "[&_[data-slot=progress-indicator]]:bg-cyan-700"}`} /><div className="mt-5 flex items-center justify-between"><button onClick={onRestock} className="text-sm font-medium text-cyan-800 hover:text-cyan-600">＋ 補充庫存</button><button onClick={onDelete} aria-label={`刪除 ${p.name}`} className="grid size-9 place-items-center rounded-xl text-slate-300 hover:bg-red-50 hover:text-red-600"><Trash2 className="size-4" /></button></div></article>; }

function AddProductDialog({ open, setOpen, submit, busy }: DialogProps) { async function save(form: FormData) { try { await submit("addProduct", Object.fromEntries(form)); setOpen(false); toast.success("用品已加入庫存"); } catch (e) { toast.error(msg(e)); } } return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="rounded-xl"><Plus />新增用品</Button></DialogTrigger><DialogContent className="rounded-3xl"><DialogHeader><DialogTitle>新增洗車用品</DialogTitle><DialogDescription>建立容量、pH、現有餘量與補貨提醒門檻。</DialogDescription></DialogHeader><form action={save} className="grid gap-4"><Field label="用品名稱"><input className={inputClass} name="name" required /></Field><div className="grid grid-cols-3 gap-3"><Field label="用途分類"><input className={inputClass} name="category" required placeholder="預洗" /></Field><Field label="pH 分類"><select className={inputClass} name="phType" defaultValue="中性"><option>酸性</option><option>中性</option><option>鹼性</option></select></Field><Field label="單位"><select className={inputClass} name="unit" defaultValue="ml"><option>ml</option><option>g</option><option>顆</option><option>片</option></select></Field></div><div className="grid grid-cols-3 gap-3"><Field label="瓶身容量"><NumberInput name="packageSize" /></Field><Field label="目前剩餘"><NumberInput name="remaining" min="0" /></Field><Field label="提醒門檻"><NumberInput name="lowThreshold" min="0" /></Field></div><DialogFooter><Button disabled={busy} type="submit" className="rounded-xl bg-cyan-950">{busy ? "儲存中…" : "儲存用品"}</Button></DialogFooter></form></DialogContent></Dialog>; }

function RestockDialog({ product, setProduct, submit, busy }: { product: Product | null; setProduct: (v: Product | null) => void; submit: Submit; busy: boolean }) { const [bottles, setBottles] = useState(1); async function save() { if (!product) return; try { await submit("restock", { productId: product.id, bottles }); setProduct(null); setBottles(1); toast.success(`已補充 ${bottles} 罐`); } catch (e) { toast.error(msg(e)); } } return <Dialog open={!!product} onOpenChange={(v) => !v && setProduct(null)}><DialogContent className="rounded-3xl"><DialogHeader><DialogTitle>補充庫存</DialogTitle><DialogDescription>{product?.name}每罐 {product && format(product.packageSize)} {product?.unit}</DialogDescription></DialogHeader><Field label="補充幾罐"><input className={inputClass} type="number" min="1" step="1" value={bottles} onChange={(e) => setBottles(Math.max(1, Number(e.target.value)))} /></Field><div className="rounded-2xl bg-cyan-50 p-4 text-sm text-cyan-900">庫存將增加 <strong>{product ? format(product.packageSize * bottles) : 0} {product?.unit}</strong></div><DialogFooter><Button disabled={busy} onClick={save} className="rounded-xl bg-cyan-950">{busy ? "處理中…" : "確認補充"}</Button></DialogFooter></DialogContent></Dialog>; }

function FlowDialog({ open, setOpen, flow, products, submit, busy }: DialogProps & { flow: WashFlow | null; products: Product[] }) { const [flowType, setFlowType] = useState("自訂流程"), [name, setName] = useState(""), [items, setItems] = useState<Record<number, number>>({}); useEffect(() => {
  if (!open) return;
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setFlowType(flow?.flowType || "自訂流程");
  setName(flow?.flowType === "自訂流程" ? flow.name : "");
  setItems(Object.fromEntries((flow?.items || []).map((i) => [i.productId, i.amount])));
}, [open, flow]); async function save() { const list = Object.entries(items).filter(([, amount]) => amount > 0).map(([productId, amount]) => ({ productId: Number(productId), amount })); try { await submit("saveFlow", { flowId: flow?.id, flowType, name, items: list }); setOpen(false); toast.success("流程設定已儲存"); } catch (e) { toast.error(msg(e)); } } return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl sm:max-w-xl"><DialogHeader><DialogTitle>{flow ? `編輯 ${flow.name}` : "新增自訂流程"}</DialogTitle><DialogDescription>設定流程名稱、預設藥劑與每次使用劑量。</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="流程類型"><select disabled={!!flow && flow.flowType !== "自訂流程"} className={inputClass} value={flowType} onChange={(e) => setFlowType(e.target.value)}><option>2PH</option><option>3PH</option><option>快速保養</option><option>自訂流程</option></select></Field>{flowType === "自訂流程" && <Field label="流程名稱"><input className={inputClass} value={name} onChange={(e) => setName(e.target.value)} placeholder="例如：雨後加強洗" /></Field>}<ProductPicker products={products} values={items} setValues={setItems} /></div><DialogFooter><Button disabled={busy} onClick={save} className="rounded-xl bg-cyan-950">{busy ? "儲存中…" : "儲存流程"}</Button></DialogFooter></DialogContent></Dialog>; }

function WashDialog({ open, setOpen, flows, products, submit, busy }: DialogProps & { flows: WashFlow[]; products: Product[] }) { const [step, setStep] = useState(1), [flowId, setFlowId] = useState<number | null>(null), [usages, setUsages] = useState<Record<number, number>>({}), [date, setDate] = useState(new Date().toISOString().slice(0, 10)), [note, setNote] = useState(""); const selectedFlow = flows.find((f) => f.id === flowId); function choose(flow: WashFlow) { setFlowId(flow.id); setUsages(Object.fromEntries(flow.items.map((i) => [i.productId, i.amount]))); } async function save() { if (!flowId) return; const list = Object.entries(usages).filter(([, amount]) => amount > 0).map(([productId, amount]) => ({ productId: Number(productId), amount })); try { await submit("logWash", { flowId, washedAt: date, note, usages: list }); setOpen(false); setStep(1); setFlowId(null); setUsages({}); setNote(""); toast.success("洗車完成，庫存已扣除"); } catch (e) { toast.error(msg(e)); } } return <Dialog open={open} onOpenChange={(v) => { setOpen(v); if (!v) setStep(1); }}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl sm:max-w-xl"><DialogHeader><DialogTitle>記錄本次洗車</DialogTitle><DialogDescription>步驟 {step} / 2　{step === 1 ? "選擇這次洗車流程" : "確認藥劑與使用劑量"}</DialogDescription></DialogHeader>{step === 1 ? <div className="grid gap-3">{flows.map((flow) => <button key={flow.id} disabled={!flow.items.length} onClick={() => choose(flow)} className={`rounded-2xl border p-4 text-left transition disabled:cursor-not-allowed disabled:opacity-45 ${flowId === flow.id ? "border-cyan-600 bg-cyan-50 ring-4 ring-cyan-600/10" : "border-slate-200 hover:border-cyan-300"}`}><div className="flex justify-between"><strong>{flow.name}</strong><span className="text-xs text-slate-400">{flow.items.length} 項藥劑</span></div><p className="mt-2 text-xs text-slate-500">{flow.items.length ? flow.items.map((i) => i.productName).join("、") : "請先到流程管理設定藥劑"}</p></button>)}<DialogFooter><Button disabled={!flowId} onClick={() => setStep(2)} className="rounded-xl bg-cyan-950">下一步：確認用量</Button></DialogFooter></div> : <div className="grid gap-4"><div className="rounded-2xl bg-cyan-950 p-4 text-white"><p className="text-xs text-cyan-200">本次流程</p><p className="mt-1 font-semibold">{selectedFlow?.name}</p></div><Field label="洗車日期"><input className={inputClass} type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field><ProductPicker products={products.filter((p) => usages[p.id] !== undefined)} values={usages} setValues={setUsages} locked /><Field label="備註（選填）"><input className={inputClass} value={note} onChange={(e) => setNote(e.target.value)} /></Field><DialogFooter><Button variant="outline" onClick={() => setStep(1)} className="rounded-xl">上一步</Button><Button disabled={busy} onClick={save} className="rounded-xl bg-cyan-950">{busy ? "扣除中…" : "確認並扣除庫存"}</Button></DialogFooter></div>}</DialogContent></Dialog>; }

function ProductPicker({ products, values, setValues, locked = false }: { products: Product[]; values: Record<number, number>; setValues: (v: Record<number, number>) => void; locked?: boolean }) { return <div className="grid gap-2">{products.map((p) => { const checked = values[p.id] !== undefined; return <div key={p.id} className={`grid grid-cols-[auto_1fr_115px] items-center gap-3 rounded-2xl border p-3 ${checked ? "border-cyan-300 bg-cyan-50" : "border-slate-200"}`}>{locked ? <Beaker className="size-4 text-cyan-700" /> : <Checkbox checked={checked} onCheckedChange={(v) => { const next = { ...values }; if (v) next[p.id] = 0; else delete next[p.id]; setValues(next); }} />}<div><p className="text-sm font-medium">{p.name}</p><p className="text-xs text-slate-500">庫存 {format(p.remaining)} {p.unit}</p></div><div className="relative"><input className={`${inputClass} pr-9`} disabled={!checked} type="number" min="0.1" max={p.remaining} step="0.1" value={checked ? values[p.id] : ""} onChange={(e) => setValues({ ...values, [p.id]: Number(e.target.value) })} /><span className="absolute right-3 top-3 text-xs text-slate-400">{p.unit}</span></div></div>; })}</div>; }

function DeleteProductDialog({ product, setProduct, submit, busy }: { product: Product | null; setProduct: (v: Product | null) => void; submit: Submit; busy: boolean }) { const flows = product?.affectedFlowNames?.split(",").filter(Boolean) || []; async function remove() { if (!product) return; try { await submit("deleteProduct", { productId: product.id }); setProduct(null); toast.success("用品已從庫存與相關流程移除"); } catch (e) { toast.error(msg(e)); } } return <AlertDialog open={!!product} onOpenChange={(v) => !v && setProduct(null)}><AlertDialogContent className="rounded-3xl"><AlertDialogHeader><AlertDialogTitle>確認移除「{product?.name}」？</AlertDialogTitle><AlertDialogDescription asChild><div className="space-y-3"><p>用品會從庫存列表移除，過去洗車紀錄會完整保留。</p>{flows.length > 0 && <div className="rounded-xl bg-amber-50 p-3 text-amber-900"><strong>也會從以下流程範本移除：</strong><p className="mt-1">{flows.join("、")}</p></div>}</div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} variant="destructive" onClick={remove}>{busy ? "移除中…" : "確認移除"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }

function HistoryList({ washes }: { washes: Wash[] }) { return <section className="rounded-[28px] border border-white bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-slate-100"><History className="size-4" /></div><div><h2 className="font-semibold">最近洗車紀錄</h2><p className="text-sm text-slate-500">保留流程、藥劑與實際用量</p></div></div>{washes.length === 0 ? <p className="py-10 text-center text-sm text-slate-400">還沒有洗車紀錄</p> : <div className="mt-5 divide-y divide-slate-100">{washes.map((w) => <div key={w.id} className="grid gap-1 py-4 sm:grid-cols-[130px_1fr]"><time className="text-sm font-medium">{new Date(w.washedAt + "T00:00:00").toLocaleDateString("zh-TW")}</time><div><p className="text-sm font-semibold text-cyan-900">{w.flowName || "舊版洗車紀錄"}</p><p className="mt-1 text-sm text-slate-700">{w.summary}</p>{w.note && <p className="mt-1 text-xs text-slate-400">{w.note}</p>}</div></div>)}</div>}</section>; }
function Metric({ icon, value, label, warning }: { icon: React.ReactNode; value: number; label: string; warning?: boolean }) { return <div className={`rounded-[28px] border p-6 shadow-sm ${warning ? "border-amber-200 bg-amber-50 text-amber-800" : "border-white bg-white"}`}><div className="size-5">{icon}</div><p className="mt-6 text-3xl font-semibold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>; }
function SectionTitle({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-semibold tracking-[.16em] text-cyan-700">{eyebrow}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{title}</h2></div>{children}</div>; }
function EmptyState({ onAdd }: { onAdd: () => void }) { return <div className="rounded-[28px] border border-dashed border-cyan-200 bg-white/70 px-6 py-14 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-cyan-100 text-cyan-800"><PackagePlus /></div><h3 className="mt-4 font-semibold">先加入第一項洗車用品</h3><Button onClick={onAdd} className="mt-5 rounded-xl bg-cyan-950"><Plus />新增用品</Button></div>; }
function Loading() { return <div className="rounded-3xl bg-white p-8 text-sm text-slate-500">正在整理庫存…</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>; }
function NumberInput(props: React.ComponentProps<"input">) { return <input {...props} className={inputClass} type="number" min={props.min ?? "0.1"} step="0.1" required />; }
function format(value: number) { return new Intl.NumberFormat("zh-TW", { maximumFractionDigits: 1 }).format(value); }
function msg(error: unknown) { return error instanceof Error ? error.message : "操作失敗"; }
function phClass(ph: Product["phType"]) { return ph === "酸性" ? "bg-rose-50 text-rose-700" : ph === "鹼性" ? "bg-violet-50 text-violet-700" : "bg-emerald-50 text-emerald-700"; }
type DialogProps = { open: boolean; setOpen: (v: boolean) => void; submit: Submit; busy: boolean };
