"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Archive, Droplets, History, PackagePlus, Plus, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Toaster } from "@/components/ui/sonner";

type Product = { id: number; name: string; category: string; unit: string; packageSize: number; remaining: number; lowThreshold: number };
type Wash = { id: string; washedAt: string; note: string | null; summary: string | null };
type Data = { products: Product[]; washes: Wash[] };
const inputClass = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-cyan-600 focus:ring-4 focus:ring-cyan-600/10";

export default function InventoryApp() {
  const [data, setData] = useState<Data>({ products: [], washes: [] });
  const [loading, setLoading] = useState(true), [addOpen, setAddOpen] = useState(false), [washOpen, setWashOpen] = useState(false);
  const [restock, setRestock] = useState<Product | null>(null);
  const [selected, setSelected] = useState<Record<number, number>>({});
  const load = useCallback(async () => { const r = await fetch("/api/inventory", { cache: "no-store" }); if (!r.ok) throw new Error(); setData(await r.json()); setLoading(false); }, []);
  useEffect(() => {
    // Initial client hydration fetches the private inventory after mount.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load().catch(() => { setLoading(false); toast.error("暫時無法讀取庫存"); });
  }, [load]);
  async function submit(action: string, payload: Record<string, unknown>) { const r = await fetch("/api/inventory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const result = await r.json().catch(() => ({})); if (!r.ok) throw new Error(result.error || "操作失敗"); await load(); }
  const lowStock = useMemo(() => data.products.filter((p) => p.remaining <= p.lowThreshold), [data.products]);
  const totalRemaining = data.products.length ? Math.round(data.products.reduce((sum, p) => sum + Math.min(100, p.remaining / p.packageSize * 100), 0) / data.products.length) : 0;

  return <main className="min-h-screen bg-[#f2f7f7] text-slate-950"><Toaster position="top-center" richColors />
    <header className="border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-2xl bg-cyan-950 text-cyan-100"><Droplets className="size-5" /></div><div><p className="text-xs font-semibold tracking-[.18em] text-cyan-700">CAR CARE</p><h1 className="font-semibold tracking-tight">洗車用品庫存</h1></div></div><Button onClick={() => setWashOpen(true)} className="rounded-xl bg-cyan-950 text-white hover:bg-cyan-900"><Sparkles className="size-4" />記錄洗車</Button></div></header>
    <div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 sm:py-10">
      <section className="grid gap-4 md:grid-cols-[1.45fr_.8fr_.8fr]"><div className="relative overflow-hidden rounded-[28px] bg-cyan-950 p-6 text-white shadow-[0_18px_55px_rgba(8,51,68,.17)] sm:p-8"><div className="absolute -right-16 -top-20 size-52 rounded-full border-[28px] border-cyan-700/30" /><p className="text-sm text-cyan-200">目前庫存概況</p><div className="mt-8 flex items-end gap-3"><strong className="text-6xl font-semibold tracking-[-.06em]">{loading ? "—" : totalRemaining}</strong><span className="pb-2 text-cyan-200">% 平均剩餘</span></div><p className="mt-3 text-sm text-cyan-100/75">共管理 {data.products.length} 項用品</p></div><Metric icon={<Archive />} value={data.products.length} label="庫存品項" /><Metric icon={<AlertTriangle />} value={lowStock.length} label="需要補貨" warning={lowStock.length > 0} /></section>
      <section className="mt-9"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-semibold tracking-[.16em] text-cyan-700">INVENTORY</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">用品餘量</h2></div><AddProductDialog open={addOpen} setOpen={setAddOpen} submit={submit} /></div>
        {loading ? <div className="rounded-3xl bg-white p-8 text-sm text-slate-500">正在整理庫存…</div> : data.products.length === 0 ? <EmptyState onAdd={() => setAddOpen(true)} /> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.products.map((p) => <ProductCard key={p.id} product={p} onRestock={() => setRestock(p)} />)}</div>}
      </section>
      <section className="mt-10 rounded-[28px] border border-white bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-slate-100"><History className="size-4" /></div><div><h2 className="font-semibold">最近洗車紀錄</h2><p className="text-sm text-slate-500">每次用量都會自動反映在庫存</p></div></div>{data.washes.length === 0 ? <p className="py-10 text-center text-sm text-slate-400">還沒有洗車紀錄</p> : <div className="mt-5 divide-y divide-slate-100">{data.washes.map((w) => <div key={w.id} className="grid gap-1 py-4 sm:grid-cols-[130px_1fr]"><time className="text-sm font-medium">{new Date(w.washedAt + "T00:00:00").toLocaleDateString("zh-TW")}</time><div><p className="text-sm text-slate-700">{w.summary}</p>{w.note && <p className="mt-1 text-xs text-slate-400">{w.note}</p>}</div></div>)}</div>}</section>
    </div><WashDialog open={washOpen} setOpen={setWashOpen} products={data.products} selected={selected} setSelected={setSelected} submit={submit} /><RestockDialog product={restock} setProduct={setRestock} submit={submit} /></main>;
}

function Metric({ icon, value, label, warning }: { icon: React.ReactNode; value: number; label: string; warning?: boolean }) { return <div className={`rounded-[28px] border p-6 shadow-sm ${warning ? "border-amber-200 bg-amber-50 text-amber-800" : "border-white bg-white"}`}><div className="size-5">{icon}</div><p className="mt-6 text-3xl font-semibold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>; }
function ProductCard({ product: p, onRestock }: { product: Product; onRestock: () => void }) { const percent = Math.max(0, Math.min(100, p.remaining / p.packageSize * 100)), low = p.remaining <= p.lowThreshold; return <article className="rounded-3xl border border-white bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{p.category}</span><h3 className="mt-3 font-semibold">{p.name}</h3></div>{low && <span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-medium text-amber-800">補貨</span>}</div><div className="mt-8 flex items-baseline justify-between"><span className="text-3xl font-semibold tracking-tight">{formatNumber(p.remaining)}</span><span className="text-sm text-slate-500">{p.unit} / {formatNumber(p.packageSize)} {p.unit}</span></div><Progress value={percent} className={`mt-3 h-2 ${low ? "[&_[data-slot=progress-indicator]]:bg-amber-500" : "[&_[data-slot=progress-indicator]]:bg-cyan-700"}`} /><button onClick={onRestock} className="mt-5 text-sm font-medium text-cyan-800 hover:text-cyan-600">＋ 補充庫存</button></article>; }
function EmptyState({ onAdd }: { onAdd: () => void }) { return <div className="rounded-[28px] border border-dashed border-cyan-200 bg-white/70 px-6 py-14 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-cyan-100 text-cyan-800"><PackagePlus /></div><h3 className="mt-4 font-semibold">先加入第一項洗車用品</h3><p className="mt-2 text-sm text-slate-500">輸入瓶身容量與目前剩餘量，就能開始追蹤。</p><Button onClick={onAdd} className="mt-5 rounded-xl bg-cyan-950"><Plus />新增用品</Button></div>; }

function AddProductDialog({ open, setOpen, submit }: DialogProps) { async function save(form: FormData) { try { await submit("addProduct", Object.fromEntries(form)); setOpen(false); toast.success("用品已加入庫存"); } catch (e) { toast.error(message(e)); } } return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" className="rounded-xl"><Plus />新增用品</Button></DialogTrigger><DialogContent className="rounded-3xl"><DialogHeader><DialogTitle>新增洗車用品</DialogTitle><DialogDescription>建立容量、現有餘量與補貨提醒門檻。</DialogDescription></DialogHeader><form action={save} className="grid gap-4"><Field label="用品名稱"><input className={inputClass} name="name" required placeholder="例如：PRÌMUS 預洗液" /></Field><div className="grid grid-cols-2 gap-3"><Field label="分類"><input className={inputClass} name="category" required placeholder="預洗" /></Field><Field label="單位"><select className={inputClass} name="unit" defaultValue="ml"><option>ml</option><option>g</option><option>顆</option><option>片</option></select></Field></div><div className="grid grid-cols-3 gap-3"><Field label="瓶身容量"><NumberInput name="packageSize" /></Field><Field label="目前剩餘"><NumberInput name="remaining" min="0" /></Field><Field label="提醒門檻"><NumberInput name="lowThreshold" min="0" /></Field></div><DialogFooter><Button type="submit" className="rounded-xl bg-cyan-950">儲存用品</Button></DialogFooter></form></DialogContent></Dialog>; }
function WashDialog({ open, setOpen, products, selected, setSelected, submit }: DialogProps & { products: Product[]; selected: Record<number, number>; setSelected: (v: Record<number, number>) => void }) { async function save(form: FormData) { const usages = Object.entries(selected).filter(([, amount]) => amount > 0).map(([productId, amount]) => ({ productId: Number(productId), amount })); if (!usages.length) return toast.error("請至少選擇一項用品並填寫用量"); try { await submit("logWash", { washedAt: form.get("washedAt"), note: form.get("note"), usages }); setOpen(false); setSelected({}); toast.success("洗車紀錄完成，庫存已扣除"); } catch (e) { toast.error(message(e)); } } return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl sm:max-w-xl"><DialogHeader><DialogTitle>記錄本次洗車</DialogTitle><DialogDescription>勾選本次使用的用品，填入實際用量。</DialogDescription></DialogHeader>{products.length === 0 ? <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">請先新增洗車用品。</p> : <form action={save} className="grid gap-4"><Field label="洗車日期"><input className={inputClass} name="washedAt" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></Field><div className="grid gap-2">{products.map((p) => { const checked = selected[p.id] !== undefined; return <div key={p.id} className={`grid grid-cols-[auto_1fr_110px] items-center gap-3 rounded-2xl border p-3 ${checked ? "border-cyan-300 bg-cyan-50" : "border-slate-200"}`}><Checkbox checked={checked} onCheckedChange={(v) => { const next = { ...selected }; if (v) next[p.id] = 0; else delete next[p.id]; setSelected(next); }} aria-label={`使用 ${p.name}`} /><div><p className="text-sm font-medium">{p.name}</p><p className="text-xs text-slate-500">剩 {formatNumber(p.remaining)} {p.unit}</p></div><div className="relative"><input className={`${inputClass} pr-9`} disabled={!checked} type="number" min="0.1" max={p.remaining} step="0.1" value={checked ? selected[p.id] : ""} onChange={(e) => setSelected({ ...selected, [p.id]: Number(e.target.value) })} placeholder="用量" /><span className="absolute right-3 top-3 text-xs text-slate-400">{p.unit}</span></div></div>; })}</div><Field label="備註（選填）"><input className={inputClass} name="note" placeholder="例如：本次有跑高速，蟲屍較多" /></Field><DialogFooter><Button type="submit" className="rounded-xl bg-cyan-950">完成並扣除庫存</Button></DialogFooter></form>}</DialogContent></Dialog>; }
function RestockDialog({ product, setProduct, submit }: { product: Product | null; setProduct: (v: Product | null) => void; submit: Submit }) { async function save(form: FormData) { if (!product) return; try { await submit("restock", { productId: product.id, amount: form.get("amount") }); setProduct(null); toast.success("庫存已補充"); } catch (e) { toast.error(message(e)); } } return <Dialog open={!!product} onOpenChange={(v) => !v && setProduct(null)}><DialogContent className="rounded-3xl"><DialogHeader><DialogTitle>補充庫存</DialogTitle><DialogDescription>{product?.name}目前剩餘 {product && formatNumber(product.remaining)} {product?.unit}</DialogDescription></DialogHeader><form action={save} className="grid gap-4"><Field label={`新增數量（${product?.unit || ""}）`}><NumberInput name="amount" defaultValue={product?.packageSize} /></Field><DialogFooter><Button type="submit" className="rounded-xl bg-cyan-950">確認補充</Button></DialogFooter></form></DialogContent></Dialog>; }

type Submit = (action: string, payload: Record<string, unknown>) => Promise<void>;
type DialogProps = { open: boolean; setOpen: (v: boolean) => void; submit: Submit };
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>; }
function NumberInput(props: React.ComponentProps<"input">) { return <input {...props} className={inputClass} type="number" min={props.min ?? "0.1"} step="0.1" required />; }
function formatNumber(value: number) { return new Intl.NumberFormat("zh-TW", { maximumFractionDigits: 1 }).format(value); }
function message(error: unknown) { return error instanceof Error ? error.message : "操作失敗"; }
